spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root@39}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-minimum-32-characters}
  expiration: 1d

app:
  cors:
    allowed-origins: 
      - http://localhost:3000
  recent-articles:
    max-size: 10
